// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Invite struct {
	Code     string
	Username string
}

type Ticketlog struct {
	Date            pgtype.Timestamptz
	Username        string
	TandemCount     int32
	InstructorCount int32
	BlueTicketCount int32
	PinkTicketCount int32
	KitHireCount    int32
}

type User struct {
	Username string
	Password string
	Admin    bool
}
