// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ticketlog.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrUpdateTicketlog = `-- name: CreateOrUpdateTicketlog :exec
INSERT INTO TicketLog (date, username, tandem_count, instructor_count, blue_ticket_count, pink_ticket_count, kit_hire_count)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (date, username) DO UPDATE SET
    tandem_count = EXCLUDED.tandem_count,
    instructor_count = EXCLUDED.instructor_count,
    blue_ticket_count = EXCLUDED.blue_ticket_count,
    pink_ticket_count = EXCLUDED.pink_ticket_count,
    kit_hire_count = EXCLUDED.kit_hire_count
`

type CreateOrUpdateTicketlogParams struct {
	Date            pgtype.Timestamptz
	Username        string
	TandemCount     int32
	InstructorCount int32
	BlueTicketCount int32
	PinkTicketCount int32
	KitHireCount    int32
}

func (q *Queries) CreateOrUpdateTicketlog(ctx context.Context, arg CreateOrUpdateTicketlogParams) error {
	_, err := q.db.Exec(ctx, createOrUpdateTicketlog,
		arg.Date,
		arg.Username,
		arg.TandemCount,
		arg.InstructorCount,
		arg.BlueTicketCount,
		arg.PinkTicketCount,
		arg.KitHireCount,
	)
	return err
}

const getTicketlogByDate = `-- name: GetTicketlogByDate :one
SELECT date, username, tandem_count, instructor_count, blue_ticket_count, pink_ticket_count, kit_hire_count FROM TicketLog WHERE date = $1 AND username = $2
`

type GetTicketlogByDateParams struct {
	Date     pgtype.Timestamptz
	Username string
}

func (q *Queries) GetTicketlogByDate(ctx context.Context, arg GetTicketlogByDateParams) (Ticketlog, error) {
	row := q.db.QueryRow(ctx, getTicketlogByDate, arg.Date, arg.Username)
	var i Ticketlog
	err := row.Scan(
		&i.Date,
		&i.Username,
		&i.TandemCount,
		&i.InstructorCount,
		&i.BlueTicketCount,
		&i.PinkTicketCount,
		&i.KitHireCount,
	)
	return i, err
}

const getTicketlogsBetweenDates = `-- name: GetTicketlogsBetweenDates :many
SELECT date, username, tandem_count, instructor_count, blue_ticket_count, pink_ticket_count, kit_hire_count FROM TicketLog WHERE date >= $1 AND date <= $2 AND username = $3 ORDER BY date ASC
`

type GetTicketlogsBetweenDatesParams struct {
	Date     pgtype.Timestamptz
	Date_2   pgtype.Timestamptz
	Username string
}

func (q *Queries) GetTicketlogsBetweenDates(ctx context.Context, arg GetTicketlogsBetweenDatesParams) ([]Ticketlog, error) {
	rows, err := q.db.Query(ctx, getTicketlogsBetweenDates, arg.Date, arg.Date_2, arg.Username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticketlog
	for rows.Next() {
		var i Ticketlog
		if err := rows.Scan(
			&i.Date,
			&i.Username,
			&i.TandemCount,
			&i.InstructorCount,
			&i.BlueTicketCount,
			&i.PinkTicketCount,
			&i.KitHireCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
