// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
)

const createInvite = `-- name: CreateInvite :exec
INSERT INTO invites (code, username) VALUES ($1, $2)
`

type CreateInviteParams struct {
	Code     string
	Username string
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.Exec(ctx, createInvite, arg.Code, arg.Username)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (username, password) VALUES ($1, $2)
`

type CreateUserParams struct {
	Username string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Username, arg.Password)
	return err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM invites WHERE code = $1
`

func (q *Queries) DeleteInvite(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, deleteInvite, code)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE username = $1
`

func (q *Queries) DeleteUser(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, deleteUser, username)
	return err
}

const getInviteByCode = `-- name: GetInviteByCode :one
SELECT code, username FROM invites WHERE code = $1
`

func (q *Queries) GetInviteByCode(ctx context.Context, code string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByCode, code)
	var i Invite
	err := row.Scan(&i.Code, &i.Username)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT username, password, admin FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(&i.Username, &i.Password, &i.Admin)
	return i, err
}

const grantAdmin = `-- name: GrantAdmin :exec
UPDATE users SET admin = TRUE WHERE username = $1
`

func (q *Queries) GrantAdmin(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, grantAdmin, username)
	return err
}

const listInvites = `-- name: ListInvites :many
SELECT code, username FROM invites
`

func (q *Queries) ListInvites(ctx context.Context) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(&i.Code, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT username, admin FROM users
`

type ListUsersRow struct {
	Username string
	Admin    bool
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.Username, &i.Admin); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAdmin = `-- name: RevokeAdmin :exec
UPDATE users SET admin = FALSE WHERE username = $1
`

func (q *Queries) RevokeAdmin(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, revokeAdmin, username)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET password = $2 WHERE username = $1
`

type UpdatePasswordParams struct {
	Username string
	Password string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.Username, arg.Password)
	return err
}
